### ISSUE TITLE
Blank default password

### ISSUE THREAD

**Issue by Michael-Stokoe** [Noogic/laravel-cli-password-reset#1]
Hi, I've just pulled this package in to use with an application and found a potential security vulnerability.

If the default password is set to an empty string in the config (Which it shouldn't, I get it), but if for some reason your laravel app can't find that config item, it will carry on execution anyways and hash an empty string.

There should potentially be an extra check in your command to make sure the password isn't getting set to an empty string.

**Comment by Noogic** [comment]
Thanks for the feedback. I'll check that as soon as possible.

**Comment by Noogic** [comment]
Fixed: https://github.com/Noogic/laravel-cli-password-reset/commit/72b71778fcaa54a367fbbe8dd3770da716cee98c
